spring.application.name=personal_dev_11862_sato_ryota


# DB接続情報
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql:medicine_db
spring.datasource.username=student
spring.datasource.password=himitu
# SQL実行出力
spring.jpa.show-sql=true
# schema.sqlとdata.sqlの自動実行
spring.sql.init.mode=always
## schema.sqlとdata.sqlの自動実行をしない設定 spring.sql.init.mode=never
server.servlet.session.timeout=2880
## セッション保持時間 2日分


# https://qiita.com/elyoshio92/items/2daf760bb6f6ddbaa618
## 上記。メール通知機能を実装する場合に必要

# シャットダウンエンドポイントを有効化
management.endpoint.shutdown.enabled=true
# エンドポイントの公開設定（Web経由で呼び出せるようにする）
management.endpoints.web.exposure.include=shutdown