/*
個人開発


①ユーザーとロール
CREATE USER student WITH PASSWORD 'himitu';
 もう作ってるはず
CREATE DATABASE medicine_db OWNER student ENCODING 'UTF-8'; 
 DBつくる　ロールをstudentに。
 
 
 postgresの操作
 ①spring.datasource.url=jdbc:postgresql:medicine_db
 アプリケーションプロパティ
 ②DB作成
 create database medicine_db;
③dbに接続
\c medicine_db

*/

DROP TABLE IF EXISTS medicine;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
	user_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(40) NOT NULL,
	user_password VARCHAR(255)
);
	

CREATE TABLE medicine (
	medicine_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	medicine_name VARCHAR(40)  NOT NULL,
	medicine_note VARCHAR(500),
	medicine_count INTEGER,
	medicine_check boolean NOT NULL DEFAULT FALSE,
	medicine_check_morning boolean NOT NULL DEFAULT FALSE,
	medicine_check_daytime boolean NOT NULL DEFAULT FALSE,
	medicine_check_night boolean NOT NULL DEFAULT FALSE,
	user_id INTEGER REFERENCES users(user_id)
);