/*
個人開発


①ユーザーとロール
CREATE USER student WITH PASSWORD 'himitu';
 もう作ってるはず
CREATE DATABASE medicine_db OWNER student ENCODING 'UTF-8'; 
 DBつくる　ロールをstudentに。
 
 
 postgresの操作
 ①spring.datasource.url=jdbc:postgresql:medicine_db
 アプリケーションプロパティ
 ②DB作成
 create database medicine_db;
③dbに接続
\c medicine_db

*/

DROP TABLE IF EXISTS medicine;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
	id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	password VARCHAR(255)
);
	

CREATE TABLE medicine (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(40)  NOT NULL,
	text VARCHAR(500),
	count INTEGER,
	medicine_check boolean NOT NULL DEFAULT FALSE,
	morning_check boolean NOT NULL DEFAULT FALSE,
	daytime_check boolean NOT NULL DEFAULT FALSE,
	night_check boolean NOT NULL DEFAULT FALSE,
	lastDate DATE,
	user_id INTEGER REFERENCES users(id)
);